name: Security Audit CI

on: [push, pull_request]

jobs:
  security_audit:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.modified, 'Cargo.toml') ||
      contains(github.event.head_commit.modified, 'Cargo.lock') ||
      contains(github.event.head_commit.modified, 'deny.toml')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 'stable'

      - name: Run Cargo Deny
        uses: EmbarkStudios/cargo-deny-action@v2.0.20
        with:
          log-level: 'error'

      - name: Run Cargo Audit
        uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}