name: Security Audit CI

on:
  push:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'deny.toml'
  pull_request:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'deny.toml'

permissions:
  contents: read

jobs:
  security_audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 'stable'

      - name: Run Cargo Deny
        uses: EmbarkStudios/cargo-deny-action@v2.0.20
        with:
          log-level: 'error'

      - name: Run Cargo Audit
        uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
